---
- hosts: all
 
  
  vars_prompt:
          - name: "rhn"
            prompt: "Enter the rhn user "
            private: no
          - name: "password"
            prompt: "Enter your password "
            private: yes
  
  tasks:
          - name: registering system
            redhat_subscription:
                    state: present
                    username: "{{ rhn }}"
                    password: "{{ password }}"
            tags: 
              - "register"

          - name: attaching system for the satellite pool
            shell: |
                    pool=$(subscription-manager list --available --matches='*Satellite Beta' | awk '/(Pool ID)|(ID de grupo)/ {print $NF}' | head -n 1)
                    subscription-manager attach --pool=$pool
            tags:
                    - "attach"

          - name: Disable all RHSM repos
            rhsm_repository:
                    name: '*'
                    state: disabled
            tags:
                    - "disable"

          - name: including the satellite beta repos
            include_vars: vars/vrepos.yml
            tags:
                    - "enable"

          - name: Enable the satellite beta repos
            rhsm_repository:
                    name: "{{ item }}"
                    state: enabled
            loop: "{{ list_of_repos }}"
            tags:
                    - "enable"

          - name: cleaning repos
            command: yum clean all
            tags:
                    - "clean"
